### ISSUE TITLE
Duplicated timeseries in CollectorRegistry

### ISSUE THREAD

**Issue by turque** [labbsr0x/flask-monitor#3]
Dears, 

I'm having difficulties using this module with pytest.

I split my pytest in multiples files for better organization.

Using flask-prometheus-metrics i d'nt have test problem whit, but whit this flask_monitor only first test file pass whit successful and the others fail

`self = <prometheus_client.registry.CollectorRegistry object at 0x7fe30a7c8220>, collector = prometheus_client.metrics.Histogram(request_seconds)

    def register(self, collector):
        """Add a collector to the registry."""
        with self._lock:
            names = self._get_names(collector)
            duplicates = set(self._names_to_collectors).intersection(names)
            if duplicates:
>               raise ValueError(
                    'Duplicated timeseries in CollectorRegistry: {0}'.format(
                        duplicates))
E               ValueError: Duplicated timeseries in CollectorRegistry: {'request_seconds_bucket', 'request_seconds_created', 'request_seconds_count', 'request_seconds_sum'}

env/lib/python3.8/site-packages/prometheus_client/registry.py:29: ValueError
`

if i merge all test-files the test pass whit successful.

Do you have ideia about this problem?

**Comment by KarineValenca** [comment]
@gutorc92

**Comment by gutorc92** [comment]
@turque, It is happen because every thread try to register the metrics and collectors do not accept it. I'm working in a fix to it.

**Comment by Ziul** [comment]
@turque could you please check if v0.0.2 solved your issue?

**Comment by turque** [comment]
@Ziul I tested it and the duplicated error did not occur but it's not generating metrics

They apscheduler dependency don't install automatically, we need install manually.

**Comment by Ziul** [comment]
@turque looks like you’re having some issues with the registry. In [v0.0.2](https://github.com/labbsr0x/flask-monitor/releases/tag/v0.0.2) we did some changes to avoid the use of a custom registry. If you are using a custom registry yet, check [this test](https://github.com/labbsr0x/flask-monitor/blob/1e83b786e5974be6e01b4615c8998a8127d8097d/tests/base_test.py#L42) where the `/metrics` route is customized to use a custom registry. If you are using a single Flask instance for those multiples files, the registry instance is being stored in `app.extensions["registry"]`.

If yet the issues continue, please share some of your tests here, so we can help you.

**Comment by turque** [comment]
@Ziul i used  custom registry like[ this test](https://github.com/labbsr0x/flask-monitor/blob/1e83b786e5974be6e01b4615c8998a8127d8097d/tests/base_test.py#L42) and it worked.
I will take more tests and reopen this issue if necessary.

One point, the apscheduler dependency don't install automatically, we need install manually, it's necessary to bb-flask-monitor version 0.0.2

**Comment by Ziul** [comment]
Missing dependency included in version 0.0.3. Thank you!
